SELECT TOP 1000
	"CURRENCY_CODE",
	"GROSS_AMOUNT",
	"NET_AMOUNT",
	"TAX_AMOUNT",
	"NODE_KEY",
	"PO_ID",
	"PARTNER_GUID_NODE_KEY",
	"LIFECYCLE_STATUS",
	"OVERALL_STATUS"
FROM "8BEB61E325A24982B1D724EA2CA03A18"."COM_TCS_SD_SOA_DB_TRANSACTION_PURCHASEORDER"